### ISSUE TITLE
Watch not watching for changes in .less files

### ISSUE THREAD

**Issue by zeyad-aql-nagwa** [arnog/esbuild-plugin-less#1]
There's an issue when I start the dev serve and changes somethin in the .less files, the watch doesn't get notified and the build isn't building until I change something in another file (.ts file for example).

I'm using a windows 10 device with node verison 14.18.1.

I already created a repo [here](https://github.com/zeyad-aql-nagwa/arnog-esbuild-plugin-less), and will create a pull request now. I just wanted to let you know of the issue.

Thanks and good luck.

**Comment by arnog** [comment]
Thanks. I have checked in a small fix that should address the issue.
